version: '3.8'

services:
  app:
    image: sample-app-lb:v2 
    networks:
      - app-net
    deploy:
      replicas: 5
  loadbalancer:
    image: nginx:latest
    container_name: app-loadbalancer
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    networks:
      - app-net
    depends_on:
      - app
networks:
  app-net:
